### ISSUE TITLE
Link to the flagship instance on github

### ISSUE THREAD

**Issue by wiki-me** [mariusor/go-littr#42]
otherwise it's harder to understand what your project is about, also harder to check if there are any visible improvements.

See lobsters [github page](https://github.com/lobsters/lobsters) as an example.

Might also be good for SEO, having a higher chance it will pop up in search results.

I am assuming here [this](https://littr.me/) is the flagship instance.

**Comment by MCMXCIII** [comment]
@wiki-me From what I can see this already exists on the page. It's just hard to find and not in your face. But it links to the github.

**Comment by wiki-me** [comment]
I think it should be [here](https://github.com/mariusor/go-littr) (basically on the read me page) under "about" like the lobsters page i linked, i looked three time and couldn't find it.

**Comment by MCMXCIII** [comment]
Oh I see what you mean I thought you meant on the page it'sself. I think this is something for the author. I am just picking up the project as I found it yesterday.

**Comment by mariusor** [comment]
Hey everyone, thank you for the interest. There is not an in-your-face as you said link, because this repo will not necessarily be the canonical one for the project.

Probably before me starting to release it as "public" I will point it to the [SourceHut project](https://sr.ht/~mariusor/brutalinks/)

However if you feel inclined to add a link to this repo in the README file, I'll gladly accept a PR, and I'll modify it at a later date.

Also, for me to be faster in replying to your issues it's better to use the [mailing list](https://sr.ht/~mariusor/brutalinks/lists)
